- lib/rails/html/sanitizer.rb
- test/sanitizer_test.rb
Fixes #31.
This lets us avoid encoding special chars twice in Rails as `strip_tags` could be written as:
```ruby
def strip_tags(html)
self.class.full_sanitizer.sanitize(html, encode_special_chars: false) # let Rails handle escaping.
end
```
I didn't document this option as it's really for our internal use. But there's a potential security vector we have to take into account here.
Alternatively, I guess we could just call `html_safe` in `strip_tags`, but that makes me feel uneasy too.
cc @rafaelfranca
> Pass options to the text method.

- lib/rails/html/sanitizer.rb
- test/sanitizer_test.rb
Fixes #30
Nokogiri would throw these errors when outputting the fragment with #to_s.
Instead call the format serializers directly and pass a UTF-8 encoding.
cc @rafaelfranca @kindjar @ncri @Junichilto
> Prevent "unknown encoding: ASCII-8BIT" errors

- rails-html-sanitizer.gemspec
> Fix homepage uri in gemspec.

- lib/rails/html/scrubbers.rb
TargetScrubber asts as reversal to PermitScrubber.
Two methods `allowed_node?` and `scrub_attribute?` is now
too much to know about implementaion of PermitScrubber.
It should simply reverse a result of parent method.
> Refactor TargetScrubber

- rails-html-sanitizer.gemspec
License filename changed, but not in gemspec.
Which results to not including the license file to gem.
> Fix license filename in gemspec

- test/sanitizer_test.rb
Hi,
I addressed #65 and noticed that some tests are failing. The tests fail because nokogiri behavior changed slightly. Tests still pass with 1.6.6.2, and fail at least since 1.6.8.1 (I didn't check which exact nokogiri release changed this behavior because I think it doesn't matter.). What changed in Nokogiri was that multiple opening tags are no longer removed, but escaped. Example:
before:
```ruby
full_sanitize("<<<a>") # => ""
```
after:
```ruby
full_sanitize("<<<a>") # => "&lt;&lt;"
```
I adjusted the tests so they pass again.
Lastly, I fixed a deprecation warning from MiniTest.
> Fix / improve tests

- README.md
- lib/rails/html/scrubbers.rb
The link to the Nokogiri Node class in the documentation is pointing to an ugly 404 page 😄 
This PR fixes the url to use the new one.
> Fix Nokogiri link in documentation

- rails-html-sanitizer.gemspec
[Build #91 is failing](https://travis-ci.org/rails/rails-html-sanitizer/jobs/509222442) because this gem restricts the Bundler version. This Pull Request fixes it.
> Use a inclusive Bundler version

- README.md
- lib/rails-html-sanitizer.rb
- lib/rails/html/sanitizer.rb
- test/sanitizer_test.rb
Safelist is easier to understand and less offensive. Chose `SafeList` because a similar ongoing effort in loofah gem: https://github.com/flavorjones/loofah/pull/158.
<kbd>[View Updated README.md](https://github.com/rails/rails-html-sanitizer/blob/911899f569e8e906ab1ee1c5be00dece1bec2431/README.md#safelistsanitizer)</kbd>
```
bundle exec rake
```
An attempt to fix the build in #90.
<details>
<summary>Original motivation rails/rails#33677, other community efforts examples</summary>
- https://github.com/rails/rails/pull/33681
- https://github.com/graphiti-api/graphiti/pull/10
- https://github.com/rails/rails/pull/33718
- https://github.com/ruby/psych/pull/378
- https://github.com/ruby/ruby/pull/2008
- https://github.com/ruby/ruby/pull/2009
- https://github.com/rubocop-hq/rubocop/pull/6464
- …
> Migrate to SafeListSanitizer

- lib/rails/html/sanitizer.rb
- test/sanitizer_test.rb
- `href` is not an [HTML element (tag)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element)
- Improved documentation
> Remove href from LinkSanitizer tags list

- lib/rails/html/scrubbers.rb
- Fix code snippet of PermitScrubber
|Before|After|
|---|---|
| <img width="567" alt="Screenshot 2019-05-10 13 40 29" src="https://user-images.githubusercontent.com/1000669/57502984-39acf380-7329-11e9-9ee3-0029565e8e29.png"> | <img width="497" alt="Screenshot 2019-05-10 13 40 39" src="https://user-images.githubusercontent.com/1000669/57502986-39acf380-7329-11e9-84e7-4996aabfcf8a.png"> |
- Wraps code references
> Improve Scrubber documentations

- lib/rails-html-sanitizer.rb
Small fix with deprecated warning:
DEPRECATION WARNING: warning: white_list_sanitizer **isdeprecated** , should be 
DEPRECATION WARNING: warning: white_list_sanitizer **is deprecated**
> Deprecated warning text, missing space

- lib/rails/html/sanitizer.rb
- lib/rails/html/scrubbers.rb
- rails-html-sanitizer.gemspec
- test/sanitizer_test.rb
Loofah revised constant names and deprecated the older constants. The resulting log noise galvanizes immediate action.
In the short term, this change removes log noise due to deprecated constants.
In long term, it's just to keep up.
> Match Loofah's API changes.

- rails-html-sanitizer.gemspec
Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/rails-html-sanitizer and be available via the rubygems API after the next release.
> Add project metadata to the gemspec

- README.md
See https://github.com/rails/rails-html-sanitizer/issues/109.
What do you think about the wording?
> Add a note for whitelisted tags by default in the TargetScrubber

- test/sanitizer_test.rb
Closes #111.
Notably, this test:
```
def test_should_sanitize_div_background_image_unicode_encoded
raw = %(background-image:\0075\0072\006C\0028'\006a\0061\0076\0061\0073\0063\0072\0069\0070\0074\003a\0061\006c\0065\0072\0074\0028.1027\0058.1053\0053\0027\0029'\0029)
assert_equal '', sanitize_css(raw)
end
```
is incorrectly encoded and has been since 2007; and should never have passed with earlier versions of Loofah. The property value `background-image:52C8'a161332904a1c5248.10278.1053379'9` is garbage, but it's not potentially harmful garbage that needs to be scrubbed.
This test was originally taken from [OWASP's XSS cheat sheet](https://owasp.org/www-community/xss-filter-evasion-cheatsheet), or a related source, and exists in that doc as:
```html
<DIV …
```
> fix css scrubbing tests

- .travis.yml
- CHANGELOG.md
- lib/rails/html/scrubbers.rb
- test/sanitizer_test.rb
Processing Instructions are no longer allowed by Rails::Html::PermitScrubber
Previously, a PI with a name (or "target") matching an allowed tag name was not scrubbed. There
are no known security issues associated with these PIs, but similar to comments it's preferred to
omit these nodes when possible from sanitized output.
Fixes #115.
> PermitScrubber does not permit Processing Instructions

- CHANGELOG.md
- lib/rails/html/scrubbers.rb
- test/scrubbers_test.rb
Some scrubbers want to allow comments through, but in v1.4.0 didn't
get the chance because only elements were passed through to
`keep_node?`.
This change allows comments and elements through, but still omits
other non-elements like processing instructions (see #115).
> fix: pass comment nodes to the scrubber

- CHANGELOG.md
- lib/rails/html/scrubbers.rb
- test/scrubbers_test.rb
This PR will make one less method call per element in a document.
Also rewrite the test coverage for PIs and comments from ab16fa4 to test behavior and not implementation.
> improve performance (slightly)

- .github/workflows/ci.yml
- test/sanitizer_test.rb
#125 reported test failures when running with Nokogiri using system (unpatched) libxml2. This PR updates the tests to accept either form of output (the tests in question are specifically checking for escaped quotes and not escaped `<` and `>` characters).
The Nokogiri patch that affects this behavior is
nokogiri/patches/libxml2/0002-Update-entities-to-remove-handling-of-ssi.patch
which was introduced to avoid server-side-include vulnerabilities, see https://github.com/sparklemotion/nokogiri/commit/4852e43
> ci: add coverage for system libxml2

- test/sanitizer_test.rb
libxml2 v2.9.14 changes how ill-formed HTML4 is fixed up in recovery mode. See [release notes for Nokogiri v1.13.5](https://github.com/sparklemotion/nokogiri/releases/tag/v1.13.5) and https://github.com/sparklemotion/nokogiri/issues/2525
> test: ensure we pass with libxml 2.9.14

- CHANGELOG.md
- README.md
- lib/rails/html/sanitizer.rb
- lib/rails/html/scrubbers.rb
- test/sanitizer_test.rb
- test/scrubbers_test.rb
By default PermitScrubber leaves behind inner content when scrubbing a
node. Setting the `prune` flag will remove the node *and* its content.
Will document in README if this is acceptable.
> Add `prune` flag to PermitScrubber

- test/sanitizer_test.rb
libxml 2.10.0 just dropped, and it contains a change to how incorrectly-opened HTML comments are parsed. This PR updates the tests to handle this behavior, which returns to the libxml 2.9.13-and-earlier behavior for comments starting with `<!`.
Related, see:
- https://github.com/sparklemotion/nokogiri/pull/2625
- https://gitlab.gnome.org/GNOME/libxml2/-/issues/380
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/e986d09cf531e77a9ab46af2d1a219072f310190
There was also a related issue opened on this repository:
- https://github.com/rails/rails-html-sanitizer/issues/130
Note that this behavior will be the default in a future Nokogiri release. This PR makes the tests compatible with all the known libxml2 behaviors.
> tests: handle libxml 2.10.0 incorrectly-opened comment parsing

- test/sanitizer_test.rb
Backport 307ecf2 so that the 1.4.x branch is green in CI.
> backport CI fixes to stay green with latest libxml2

- CHANGELOG.md
- lib/rails/html/sanitizer.rb
- lib/rails/html/sanitizer/version.rb
- lib/rails/html/scrubbers.rb
- rails-html-sanitizer.gemspec
- test/sanitizer_test.rb
Security release v1.4.4 was done in a private repo on the v1.4.x branch. This PR brings those changes to `master`.
> port: 1.4.4 changes

- .github/workflows/ci.yml
- .rubocop.yml
- Gemfile
- Rakefile
- lib/rails-html-sanitizer.rb
- lib/rails/html/sanitizer.rb
- lib/rails/html/sanitizer/version.rb
- lib/rails/html/scrubbers.rb
- rails-html-sanitizer.gemspec
- test/sanitizer_test.rb
- test/scrubbers_test.rb
In this PR:
- import `.rubocop.yml` from rails/rails
- move development dependencies from gemspec to `Gemfile`
- set required_ruby_version to ">= 2.5.0"
- correct all rubocop warnings
Note that Ruby 2.5 matches the oldest supported version of Rails (6.0/6.1).
> dev: Rails rubocop config, and drop support for ruby `< 2.5`

- .github/workflows/ci.yml
- .rdoc_options
- CHANGELOG.md
- Gemfile
- README.md
- lib/rails-html-sanitizer.rb
- lib/rails/html/sanitizer.rb
- lib/rails/html/sanitizer/version.rb
- lib/rails/html/scrubbers.rb
- rails-html-sanitizer.gemspec
- test/rails_api_test.rb
- test/sanitizer_test.rb
- test/scrubbers_test.rb
This PR introduces new variations of `LinkSanitizer`, `FullSanitizer`, and `SafeListSanitizer` that use Loofah's (Nokogiri's) HTML5 parsing functionality.
- `Rails::HTML5::FullSanitizer`
- `Rails::HTML5::LinkSanitizer`
- `Rails::HTML5::SafeListSanitizer`
It also introduces a `Rails::HTML4` module which is the new canonical home for the existing sanitizers (which implicity always used the HTML4 parser). Finally, the `Rails::Html` module has been renamed to `Rails::HTML`.
The following aliases are maintained for backwards compatibility:
- `Rails::Html` points to `Rails::HTML`
- `Rails::HTML::FullSanitizer` points to `Rails::HTML4::FullSanitizer`
- `Rails::HTML::LinkSanitizer` points to `Rails::HTML4::LinkSanitizer`
- `Rails::HTML::SafeListSanitizer` points to …
> support html5 parsing

- .github/workflows/ci.yml
- README.md
- rails-html-sanitizer.gemspec
THIS IS VARIATION 2 - see variation 1 at #164 
Require versions of Nokogiri and Loofah that support HTML5:
- loofah v2.21.x introduced Rails::HTML5::Sanitizer
- nokogiri v1.14.x is needed for loofah to subclass Nokogiri::HTML5::{Document,DocumentFragment}
Update required_ruby_version to ">= 2.7.0" to match Nokogiri's constraint for v1.14.x.
Update CI to only test supported Ruby versions.
The alternative (#164) is to continue to support older versions of Nokogiri (for Ruby 2.5) and Loofah.
> dep: update loofah and nokogiri to versions fully supporting HTML5

- CHANGELOG.md
- lib/rails/html/sanitizer.rb
- test/rails_api_test.rb
so that callers don't need to check `html5_support?` to choose the best parser available.
The conditionals are making Rails integration harder than it needs to be, see https://github.com/rails/rails/pull/48293
> feat: introduce Rails::HTML::Sanitizer.best_supported_vendor

- .github/workflows/ci.yml
Action/checkout recently launched v4 https://github.com/marketplace/actions/checkout and also we can update the ruby version 3.3.
> Bump action/checkout and ruby version in workflow

- .github/workflows/ci.yml
- .gitignore
- Gemfile.lock
- start tracking `Gemfile.lock` in git
- remove it in CI to allow various versions of Ruby to bundle correctly
> start tracking Gemfile.lock

- Gemfile
- test/sanitizer_test.rb
The Gem specifies a version of Ruby greater than or equal to 2.7.0
> Remove checks for Ruby versions no longer supported

- lib/rails/html/sanitizer.rb
This is a safe tag and a common use case for `sanitize` in Rails: It's a semantic tag that's useful when showing search results. Search results can contain user input. Hence, best practice is to run them through `sanitize`.
E.g., in my code:
```ruby
sanitize(search_hit_html, tags: %w[mark])
```
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark
> Add <mark> to DEFAULT_ALLOWED_TAGS

- lib/rails/html/scrubbers.rb
- test/scrubbers_test.rb
This PR eliminates needless operations on:
- the attributes of a node that has been removed
- the contents of an attribute that has been removed
> performance: eliminate operations on removed nodes

- CHANGELOG.md
- lib/rails/html/scrubbers.rb
- test/sanitizer_test.rb
Previously, if an invalid/unsafe tag was present, the scrubber attempted to modify the tags array. At best this modified the caller's variable. At worst it raised an exception when the array was frozen. Now it properly copies the tags when they are assigned.
Fixes #195
> fix: PermitScrubber accepts frozen tags

- .github/workflows/ci.yml
specfically the ubuntu 20.04 image has been retired and that test was no longer running.
> ci: bump the matrices
